---
kind: PersistentVolume
apiVersion: v1
metadata:
  name: pvc-nfs-webdav-server-data
  labels:
    app.kubernetes.io/name: webdav
    app.kubernetes.io/component: server
    app.kubernetes.io/instance: production
    app.kubernetes.io/part-of: webdav
spec:
  storageClassName: "freenas-nfs-manual-csi"
  capacity:
    storage: 600Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  mountOptions:
    - nfsvers=4
    - nolock
    - noatime
  csi:
    driver: org.democratic-csi.node-manual
    readOnly: false
    fsType: nfs
    volumeHandle: pvc-nfs-webdav-server-data
    volumeAttributes:
      server: storage-server-lagg.lan.theautomation.nl
      share: /mnt/r10_8tb/shared
      node_attach_driver: nfs
      provisioner_driver: node-manual

---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: pvc-nfs-webdav-server-data
  namespace: tools
  labels:
    app.kubernetes.io/name: webdav
    app.kubernetes.io/component: server
    app.kubernetes.io/instance: production
    app.kubernetes.io/part-of: webdav
  annotations:
    volume.beta.kubernetes.io/storage-class: "freenas-nfs-manual-csi"
spec:
  storageClassName: freenas-nfs-manual-csi
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 600Gi
  volumeName: pvc-nfs-webdav-server-data

---
kind: SealedSecret
apiVersion: bitnami.com/v1alpha1
metadata:
  name: webdav-server-secrets
  namespace: tools
spec:
  template:
    type: Opaque
    metadata:
      name: webdav-server-secrets
      namespace: tools
      labels:
        app.kubernetes.io/component: server
        app.kubernetes.io/instance: production
        app.kubernetes.io/name: webdav
        app.kubernetes.io/part-of: webdav
  encryptedData:
    PASSWORD: AgALERP2kYvA04fbmjHhBNo6P7Ex8ZGAtHacjHApstdWNkSsRMYcHTMCYI4IIYPzb19Tpf8Mxc83uGgGnlnuRxQ7DnT2JTBm7lBUEPvH63vWgvSxiXLpxXSNawuXWa8a6UKaO7ua2ryiQSxh8icHM8prruZzwYT0KyosTyqEPFA8igz+8rNe8ZtXuDGeTdaeTCuS5lIQ0vcPNSXd9sh3/XdjMzjC/kxPSihGoplfqRu3y+mwjbUZz4IWovSDhqleXXapA7JQASZKmubRlAgrJr05NgGIHVkuOQLdyscfy3kQSxiviysow0ioiv42QACgODVfTqAjf3qVOcdd09iIS6jqghkhWC5nOV9rBrBYMsIf/NwK4D8Mhtl0Iwv8WvzcSSjVXz6tDth8/1ETktdLjLHstFgpiaO1YBaipPVVZiHCgUWHPOkPtBLSP13F6JxAyYa6KajGgg/X+q2EuoaQxSYJ2w9z6f5JqKAXjYwW/QCv4DQ7wQhqf+MQcfsk2FukjBBsGMO+uLSMcEcsOYx0pdJNr1kMkgukaenypKFgSFzxHghchqybyCBX4fr1Qq1rBrPJNM6XFH65cSEjR/WOKjE8KAbsr8TClK/yNrqnUDzdtJ5E9fJs6LnhRMiU6ixhyINw6pzFnb3lF0FcrLuih6AcqOeHG5z/9ltFpKSaadb3DZzAk9xGWOxd3YAG11EmaIoyLIs2i3kGAlttJc0Qm6WHR3R/hHhZ0oQqD/itrsU=
    USERNAME: AgAjQtJf/I/Rgt08NleUUpwFifghpyCGgBnRyaWV6b+IJOcw6cZPFcNm8gnuADzZRnQO8B7Y7WykmwP7On4UcEGYuD7UMHIXxQUza4AD5lzDkDZaxq4EjHM2zjYu1aLO6Hl0qdqPebYFG5e7lwBz7eBnykWTZ5V9AS4Pt5gdqvsD6xzqrVzvzGPniZ4Xw6bo/k0BGv+urGBiq7rrCtavktbmi5kUQt3cbQElZX0VuxjJ88/++375Tw0YF4+5oy1kgtcbsu9Iga6ejkmMzPXQ0vybbIIgalLWRQcxI9pGFbBWIvBkEQqyeN9rmMicUAwOHzZ77aeY1cu092Y30SHj2zoZKp4aZ7e+gSRCQ5f3Ay6ecf4KghdeLJKdblU6e/8u3IiYdAYRew8JnlkkogGcSQhz5drLhvlxmQ/TzD2DZxnURXGBwG5IDLniC4q22vlSl+CRANQSljLbf+KV88TkndHabrD63BSZae/7/VOdqgX848kOFqmBuLwJbrEgXfVo7TKhf40HUiHEEu1ZU/3c43g4cDJ1ppgGoUseFzJDC+Z8DLQzifBgOA5q60zRMxF+Ct7v8LoJ3ouAtPJ7aRjA+rQWVRk5juuP2+TwLn/t4axqUNQyBrV/rRUeOKfxmW27TnbPiR7+678NMgL1fyS62FPdDIhoUn4t5/iOagS7zaSfFeLGg0g8GLFI/X/rk2aGU1b1rDhdJtFtQbpHmuo=

---
kind: ConfigMap
apiVersion: v1
metadata:
  name: webdav-server-env
  namespace: tools
  labels:
    app.kubernetes.io/name: webdav
    app.kubernetes.io/component: server
    app.kubernetes.io/instance: production
    app.kubernetes.io/part-of: webdav
data:
  UDI: "1000"
  GID: "2000"
  TZ: "Europe/Amsterdam"

---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: webdav-server
  namespace: tools
  labels:
    app.kubernetes.io/name: webdav
    app.kubernetes.io/component: server
    app.kubernetes.io/instance: production
    app.kubernetes.io/part-of: webdav
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: webdav
      app.kubernetes.io/component: server
      app.kubernetes.io/instance: production
      app.kubernetes.io/part-of: webdav
  template:
    metadata:
      labels:
        app.kubernetes.io/name: webdav
        app.kubernetes.io/component: server
        app.kubernetes.io/instance: production
        app.kubernetes.io/part-of: webdav
    spec:
      containers:
        - name: webdav-server
          image: harbor.lan.theautomation.nl/proxy-cache-dockerhub/ugeek/webdav:amd64
          ports:
            - name: http
              containerPort: 80
          envFrom:
            - configMapRef:
                name: webdav-server-env
            - secretRef:
                name: webdav-server-secrets
                optional: true
          resources: {}
          volumeMounts:
            - name: webdav-server-data
              mountPath: /media
              readOnly: false
      volumes:
        - name: webdav-server-data
          persistentVolumeClaim:
            claimName: pvc-nfs-webdav-server-data
      imagePullSecrets:
        - name: harbor-registry-creds

---
kind: Service
apiVersion: v1
metadata:
  name: webdav-server
  namespace: tools
  labels:
    app.kubernetes.io/name: webdav
    app.kubernetes.io/component: server
    app.kubernetes.io/instance: production
    app.kubernetes.io/part-of: webdav
spec:
  selector:
    app.kubernetes.io/name: webdav
    app.kubernetes.io/component: server
    app.kubernetes.io/instance: production
    app.kubernetes.io/part-of: webdav
  type: ClusterIP
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: http

---
kind: Ingress
apiVersion: networking.k8s.io/v1
metadata:
  name: webdav-server
  namespace: tools
  labels:
    app.kubernetes.io/name: webdav
    app.kubernetes.io/component: server
    app.kubernetes.io/instance: production
    app.kubernetes.io/part-of: webdav
  annotations:
    nginx.ingress.kubernetes.io/proxy-body-size: 20480m
spec:
  ingressClassName: nginx-private
  rules:
    - host: "webdav.lan.theautomation.nl"
      http:
        paths:
          - path: "/"
            pathType: Prefix
            backend:
              service:
                name: webdav-server
                port:
                  name: http
